spring:
  application:
    name: order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #        namespace: 0dab5652-e133-4987-9e45-3431c412dc15
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081
